### ISSUE TITLE
Help for coding

### ISSUE THREAD

**Issue by NoussMaster** [neg4n/trickster#4]
Hi, I'm new to Rust, and I like the language.
I'd like to translate my C code or I read and write in memory. I've seen your documentation which is well explained but I have a problem, if you could help me please.

I tested your code and it works perfectly:

```
fn main() -> Result<(), Box<dyn std::error::Error>> {
  let ctx = Process::new("fakegame")?;
  println!("example process id: {}", ctx.get_pid());

  //let kind_of_remote_var: i32 = 1337;
  let x1: i64 = 0x7ffe76269df4;

  let mut read_byte_buffer = ctx.read_memory::<i64>(x1 as *const i64 as usize)?;

  println!("Read process memory is -> {}", read_byte_buffer.read_i32::<LittleEndian>()?);
  
  let mut write_buffer = Vec::new();
  write_buffer.write_i32::<LittleEndian>(10)?;
  ctx.write_memory::<i32>(x1 as *const i32 as usize, write_buffer)?;


  Ok(())
}
```
The thing is, I'd like to separate the read and write into separate functions, like..:

```
fn read_process_memory(processname: &str, address: i64) -> Result<(), Box<dyn std::error::Error>> {
    let x = Process::new(processname);
    
    let mut read_pm = x.read_memory::<i64>(address as *const i64 as usize)?;
    
    println!("Read process memory is -> {}", read_pm.read_i32::<LittleEndian>()?);
    
    Ok(())
}
```
Unfortunately I have a mistake that says to me:
no method named read_memory found for enum std::result::Result<trickster::external::Process, anyhow::Error> in the current scope

method not found in std::result::Result<trickster::external::Process, anyhow::Error>rustc(E0599)

could you help me, thank you in advance.

**Comment by neg4n** [comment]
Hey @NoussMaster, I'm sorry for late reponse.

I don't want to spoonfeed you what to do but i can provide you some useful links instead.
1.  [The Rust book.](https://doc.rust-lang.org/book/)
2.  [The `?` operator.](https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/the-question-mark-operator-for-easier-error-handling.html)

Try to understand these concepts by yourself.  
Im closing this issue since it is not related to the `trickster` development.  

Best regards.
